apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.version: 1.16.0 (HEAD)
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
  labels:
    io.kompose.service: graphql-beta
  name: graphql-beta
spec:
  ports:
    - name: "8080"
      port: 8080
  type: LoadBalancer
  selector:
    io.kompose.service: graphql-beta
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: graphql-beta
  name: graphql-beta
spec:
  replicas: 3
  minReadySeconds: 30
  revisionHistoryLimit: 0
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      io.kompose.service: graphql-beta
  template:
    metadata:
      labels:
        io.kompose.service: graphql-beta
    spec:
      containers:
        - name: graphql-beta
          image: fintlabs.azurecr.io/graphql:1.2.0
          ports:
            - containerPort: 8080
          readinessProbe:
            initialDelaySeconds: 20
            timeoutSeconds: 5
            httpGet:
              port: 8080
              path: /graphql/actuator/health
          resources:
            limits:
              memory: "5Gi"
              cpu: "2"
          envFrom:
            - configMapRef:
                name: fint-environment
          env:
            - name: server.servlet.context-path
              value: "/graphql"
            - name: graphiql.endpoint.graphql
              value: "/graphql/graphql"
            - name: fint.endpoint.root
              value: "https://beta.felleskomponent.no"
            - name: spring.main.allow-bean-definition-overriding
              value: "true"
            - name: spring.codec.max-in-memory-size
              value: "50000000"
            - name: fint.webclient.connection-provider.maxLifeTime
              value: "PT15M"