apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.version: 1.16.0 (HEAD)
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
  labels:
    io.kompose.service: graphql-beta
  name: graphql-beta
spec:
  ports:
    - name: "8080"
      port: 8080
  type: LoadBalancer
  selector:
    io.kompose.service: graphql-beta
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: graphql-beta
  name: graphql-beta
spec:
  replicas: 1
  minReadySeconds: 30
  revisionHistoryLimit: 0
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      io.kompose.service: graphql-beta
  template:
    metadata:
      labels:
        io.kompose.service: graphql-beta
    spec:
      containers:
        - name: graphql-beta
          image: fintlabs.azurecr.io/graphql:PR-15.1
          ports:
            - containerPort: 8080
          readinessProbe:
            initialDelaySeconds: 30
            timeoutSeconds: 5
            httpGet:
              port: 8080
              path: /graphql/actuator/health
          resources:
            limits:
              memory: "1.5Gi"
              cpu: "1000m"
          env:
            - name: TZ
              value: Europe/Oslo
            - name: JAVA_OPTS
              value: -Xmx1G
            - name: server.servlet.context-path
              value: "/graphql"
            - name: graphiql.endpoint.graphql
              value: "/graphql/graphql"
            - name: fint.endpoint.root
              value: "https://beta.felleskomponent.no"
            - name: logging.level.org.springframework.web.reactive.function.client.ExchangeFunctions
              value: "DEBUG"
