fint:
  endpoint:
    root: https://traefik.traefik-v2
  webclient:
    connect-timeout-ms: 10000
    response-timeout: PT10S
    connection-provider:
      maxConnections: 100
      acquireTimeout: 2000
      acquireMaxCount: -1
      maxIdleTime: PT30S
      maxLifeTime: PT90S
  graphql:
    async-request-timeout: PT1M55S
    query-timeout: PT1M50S

graphql:
  servlet:
    exception-handlers-enabled: true
    async:
      enabled: true

server:
  forward-headers-strategy: framework

spring:
  threads:
    virtual:
      enabled: true

logging:
  level:
    no.fint.graphql: INFO
